// Code generated by mockery 2.9.4. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// Session is an autogenerated mock type for the Session type
type Session struct {
	mock.Mock
}

// Delete provides a mock function with given fields:
func (_m *Session) Delete() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserID provides a mock function with given fields:
func (_m *Session) UserID() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
