// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"doublequote/ent/collection"
	"doublequote/ent/collectionentry"
	"doublequote/ent/entry"
	"doublequote/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CollectionEntryUpdate is the builder for updating CollectionEntry entities.
type CollectionEntryUpdate struct {
	config
	hooks    []Hook
	mutation *CollectionEntryMutation
}

// Where appends a list predicates to the CollectionEntryUpdate builder.
func (ceu *CollectionEntryUpdate) Where(ps ...predicate.CollectionEntry) *CollectionEntryUpdate {
	ceu.mutation.Where(ps...)
	return ceu
}

// SetIsRead sets the "is_read" field.
func (ceu *CollectionEntryUpdate) SetIsRead(b bool) *CollectionEntryUpdate {
	ceu.mutation.SetIsRead(b)
	return ceu
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (ceu *CollectionEntryUpdate) SetNillableIsRead(b *bool) *CollectionEntryUpdate {
	if b != nil {
		ceu.SetIsRead(*b)
	}
	return ceu
}

// SetCollectionID sets the "collection_id" field.
func (ceu *CollectionEntryUpdate) SetCollectionID(i int) *CollectionEntryUpdate {
	ceu.mutation.ResetCollectionID()
	ceu.mutation.SetCollectionID(i)
	return ceu
}

// AddCollectionID adds i to the "collection_id" field.
func (ceu *CollectionEntryUpdate) AddCollectionID(i int) *CollectionEntryUpdate {
	ceu.mutation.AddCollectionID(i)
	return ceu
}

// SetEntryID sets the "entry_id" field.
func (ceu *CollectionEntryUpdate) SetEntryID(i int) *CollectionEntryUpdate {
	ceu.mutation.ResetEntryID()
	ceu.mutation.SetEntryID(i)
	return ceu
}

// AddEntryID adds i to the "entry_id" field.
func (ceu *CollectionEntryUpdate) AddEntryID(i int) *CollectionEntryUpdate {
	ceu.mutation.AddEntryID(i)
	return ceu
}

// SetUpdatedAt sets the "updated_at" field.
func (ceu *CollectionEntryUpdate) SetUpdatedAt(t time.Time) *CollectionEntryUpdate {
	ceu.mutation.SetUpdatedAt(t)
	return ceu
}

// AddCollectionIDs adds the "collection" edge to the Collection entity by IDs.
func (ceu *CollectionEntryUpdate) AddCollectionIDs(ids ...int) *CollectionEntryUpdate {
	ceu.mutation.AddCollectionIDs(ids...)
	return ceu
}

// AddCollection adds the "collection" edges to the Collection entity.
func (ceu *CollectionEntryUpdate) AddCollection(c ...*Collection) *CollectionEntryUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ceu.AddCollectionIDs(ids...)
}

// AddEntryIDs adds the "entry" edge to the Entry entity by IDs.
func (ceu *CollectionEntryUpdate) AddEntryIDs(ids ...int) *CollectionEntryUpdate {
	ceu.mutation.AddEntryIDs(ids...)
	return ceu
}

// AddEntry adds the "entry" edges to the Entry entity.
func (ceu *CollectionEntryUpdate) AddEntry(e ...*Entry) *CollectionEntryUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return ceu.AddEntryIDs(ids...)
}

// Mutation returns the CollectionEntryMutation object of the builder.
func (ceu *CollectionEntryUpdate) Mutation() *CollectionEntryMutation {
	return ceu.mutation
}

// ClearCollection clears all "collection" edges to the Collection entity.
func (ceu *CollectionEntryUpdate) ClearCollection() *CollectionEntryUpdate {
	ceu.mutation.ClearCollection()
	return ceu
}

// RemoveCollectionIDs removes the "collection" edge to Collection entities by IDs.
func (ceu *CollectionEntryUpdate) RemoveCollectionIDs(ids ...int) *CollectionEntryUpdate {
	ceu.mutation.RemoveCollectionIDs(ids...)
	return ceu
}

// RemoveCollection removes "collection" edges to Collection entities.
func (ceu *CollectionEntryUpdate) RemoveCollection(c ...*Collection) *CollectionEntryUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ceu.RemoveCollectionIDs(ids...)
}

// ClearEntry clears all "entry" edges to the Entry entity.
func (ceu *CollectionEntryUpdate) ClearEntry() *CollectionEntryUpdate {
	ceu.mutation.ClearEntry()
	return ceu
}

// RemoveEntryIDs removes the "entry" edge to Entry entities by IDs.
func (ceu *CollectionEntryUpdate) RemoveEntryIDs(ids ...int) *CollectionEntryUpdate {
	ceu.mutation.RemoveEntryIDs(ids...)
	return ceu
}

// RemoveEntry removes "entry" edges to Entry entities.
func (ceu *CollectionEntryUpdate) RemoveEntry(e ...*Entry) *CollectionEntryUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return ceu.RemoveEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ceu *CollectionEntryUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	ceu.defaults()
	if len(ceu.hooks) == 0 {
		affected, err = ceu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CollectionEntryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ceu.mutation = mutation
			affected, err = ceu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ceu.hooks) - 1; i >= 0; i-- {
			if ceu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ceu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ceu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ceu *CollectionEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := ceu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ceu *CollectionEntryUpdate) Exec(ctx context.Context) error {
	_, err := ceu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ceu *CollectionEntryUpdate) ExecX(ctx context.Context) {
	if err := ceu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ceu *CollectionEntryUpdate) defaults() {
	if _, ok := ceu.mutation.UpdatedAt(); !ok {
		v := collectionentry.UpdateDefaultUpdatedAt()
		ceu.mutation.SetUpdatedAt(v)
	}
}

func (ceu *CollectionEntryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   collectionentry.Table,
			Columns: collectionentry.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: collectionentry.FieldID,
			},
		},
	}
	if ps := ceu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ceu.mutation.IsRead(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: collectionentry.FieldIsRead,
		})
	}
	if value, ok := ceu.mutation.CollectionID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: collectionentry.FieldCollectionID,
		})
	}
	if value, ok := ceu.mutation.AddedCollectionID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: collectionentry.FieldCollectionID,
		})
	}
	if value, ok := ceu.mutation.EntryID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: collectionentry.FieldEntryID,
		})
	}
	if value, ok := ceu.mutation.AddedEntryID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: collectionentry.FieldEntryID,
		})
	}
	if value, ok := ceu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: collectionentry.FieldUpdatedAt,
		})
	}
	if ceu.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.CollectionTable,
			Columns: collectionentry.CollectionPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: collection.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ceu.mutation.RemovedCollectionIDs(); len(nodes) > 0 && !ceu.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.CollectionTable,
			Columns: collectionentry.CollectionPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: collection.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ceu.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.CollectionTable,
			Columns: collectionentry.CollectionPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: collection.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ceu.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.EntryTable,
			Columns: collectionentry.EntryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: entry.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ceu.mutation.RemovedEntryIDs(); len(nodes) > 0 && !ceu.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.EntryTable,
			Columns: collectionentry.EntryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: entry.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ceu.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.EntryTable,
			Columns: collectionentry.EntryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: entry.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ceu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collectionentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CollectionEntryUpdateOne is the builder for updating a single CollectionEntry entity.
type CollectionEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CollectionEntryMutation
}

// SetIsRead sets the "is_read" field.
func (ceuo *CollectionEntryUpdateOne) SetIsRead(b bool) *CollectionEntryUpdateOne {
	ceuo.mutation.SetIsRead(b)
	return ceuo
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (ceuo *CollectionEntryUpdateOne) SetNillableIsRead(b *bool) *CollectionEntryUpdateOne {
	if b != nil {
		ceuo.SetIsRead(*b)
	}
	return ceuo
}

// SetCollectionID sets the "collection_id" field.
func (ceuo *CollectionEntryUpdateOne) SetCollectionID(i int) *CollectionEntryUpdateOne {
	ceuo.mutation.ResetCollectionID()
	ceuo.mutation.SetCollectionID(i)
	return ceuo
}

// AddCollectionID adds i to the "collection_id" field.
func (ceuo *CollectionEntryUpdateOne) AddCollectionID(i int) *CollectionEntryUpdateOne {
	ceuo.mutation.AddCollectionID(i)
	return ceuo
}

// SetEntryID sets the "entry_id" field.
func (ceuo *CollectionEntryUpdateOne) SetEntryID(i int) *CollectionEntryUpdateOne {
	ceuo.mutation.ResetEntryID()
	ceuo.mutation.SetEntryID(i)
	return ceuo
}

// AddEntryID adds i to the "entry_id" field.
func (ceuo *CollectionEntryUpdateOne) AddEntryID(i int) *CollectionEntryUpdateOne {
	ceuo.mutation.AddEntryID(i)
	return ceuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ceuo *CollectionEntryUpdateOne) SetUpdatedAt(t time.Time) *CollectionEntryUpdateOne {
	ceuo.mutation.SetUpdatedAt(t)
	return ceuo
}

// AddCollectionIDs adds the "collection" edge to the Collection entity by IDs.
func (ceuo *CollectionEntryUpdateOne) AddCollectionIDs(ids ...int) *CollectionEntryUpdateOne {
	ceuo.mutation.AddCollectionIDs(ids...)
	return ceuo
}

// AddCollection adds the "collection" edges to the Collection entity.
func (ceuo *CollectionEntryUpdateOne) AddCollection(c ...*Collection) *CollectionEntryUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ceuo.AddCollectionIDs(ids...)
}

// AddEntryIDs adds the "entry" edge to the Entry entity by IDs.
func (ceuo *CollectionEntryUpdateOne) AddEntryIDs(ids ...int) *CollectionEntryUpdateOne {
	ceuo.mutation.AddEntryIDs(ids...)
	return ceuo
}

// AddEntry adds the "entry" edges to the Entry entity.
func (ceuo *CollectionEntryUpdateOne) AddEntry(e ...*Entry) *CollectionEntryUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return ceuo.AddEntryIDs(ids...)
}

// Mutation returns the CollectionEntryMutation object of the builder.
func (ceuo *CollectionEntryUpdateOne) Mutation() *CollectionEntryMutation {
	return ceuo.mutation
}

// ClearCollection clears all "collection" edges to the Collection entity.
func (ceuo *CollectionEntryUpdateOne) ClearCollection() *CollectionEntryUpdateOne {
	ceuo.mutation.ClearCollection()
	return ceuo
}

// RemoveCollectionIDs removes the "collection" edge to Collection entities by IDs.
func (ceuo *CollectionEntryUpdateOne) RemoveCollectionIDs(ids ...int) *CollectionEntryUpdateOne {
	ceuo.mutation.RemoveCollectionIDs(ids...)
	return ceuo
}

// RemoveCollection removes "collection" edges to Collection entities.
func (ceuo *CollectionEntryUpdateOne) RemoveCollection(c ...*Collection) *CollectionEntryUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ceuo.RemoveCollectionIDs(ids...)
}

// ClearEntry clears all "entry" edges to the Entry entity.
func (ceuo *CollectionEntryUpdateOne) ClearEntry() *CollectionEntryUpdateOne {
	ceuo.mutation.ClearEntry()
	return ceuo
}

// RemoveEntryIDs removes the "entry" edge to Entry entities by IDs.
func (ceuo *CollectionEntryUpdateOne) RemoveEntryIDs(ids ...int) *CollectionEntryUpdateOne {
	ceuo.mutation.RemoveEntryIDs(ids...)
	return ceuo
}

// RemoveEntry removes "entry" edges to Entry entities.
func (ceuo *CollectionEntryUpdateOne) RemoveEntry(e ...*Entry) *CollectionEntryUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return ceuo.RemoveEntryIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ceuo *CollectionEntryUpdateOne) Select(field string, fields ...string) *CollectionEntryUpdateOne {
	ceuo.fields = append([]string{field}, fields...)
	return ceuo
}

// Save executes the query and returns the updated CollectionEntry entity.
func (ceuo *CollectionEntryUpdateOne) Save(ctx context.Context) (*CollectionEntry, error) {
	var (
		err  error
		node *CollectionEntry
	)
	ceuo.defaults()
	if len(ceuo.hooks) == 0 {
		node, err = ceuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CollectionEntryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ceuo.mutation = mutation
			node, err = ceuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ceuo.hooks) - 1; i >= 0; i-- {
			if ceuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ceuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ceuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ceuo *CollectionEntryUpdateOne) SaveX(ctx context.Context) *CollectionEntry {
	node, err := ceuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ceuo *CollectionEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := ceuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ceuo *CollectionEntryUpdateOne) ExecX(ctx context.Context) {
	if err := ceuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ceuo *CollectionEntryUpdateOne) defaults() {
	if _, ok := ceuo.mutation.UpdatedAt(); !ok {
		v := collectionentry.UpdateDefaultUpdatedAt()
		ceuo.mutation.SetUpdatedAt(v)
	}
}

func (ceuo *CollectionEntryUpdateOne) sqlSave(ctx context.Context) (_node *CollectionEntry, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   collectionentry.Table,
			Columns: collectionentry.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: collectionentry.FieldID,
			},
		},
	}
	id, ok := ceuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CollectionEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ceuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collectionentry.FieldID)
		for _, f := range fields {
			if !collectionentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != collectionentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ceuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ceuo.mutation.IsRead(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: collectionentry.FieldIsRead,
		})
	}
	if value, ok := ceuo.mutation.CollectionID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: collectionentry.FieldCollectionID,
		})
	}
	if value, ok := ceuo.mutation.AddedCollectionID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: collectionentry.FieldCollectionID,
		})
	}
	if value, ok := ceuo.mutation.EntryID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: collectionentry.FieldEntryID,
		})
	}
	if value, ok := ceuo.mutation.AddedEntryID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: collectionentry.FieldEntryID,
		})
	}
	if value, ok := ceuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: collectionentry.FieldUpdatedAt,
		})
	}
	if ceuo.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.CollectionTable,
			Columns: collectionentry.CollectionPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: collection.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ceuo.mutation.RemovedCollectionIDs(); len(nodes) > 0 && !ceuo.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.CollectionTable,
			Columns: collectionentry.CollectionPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: collection.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ceuo.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.CollectionTable,
			Columns: collectionentry.CollectionPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: collection.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ceuo.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.EntryTable,
			Columns: collectionentry.EntryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: entry.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ceuo.mutation.RemovedEntryIDs(); len(nodes) > 0 && !ceuo.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.EntryTable,
			Columns: collectionentry.EntryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: entry.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ceuo.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   collectionentry.EntryTable,
			Columns: collectionentry.EntryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: entry.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CollectionEntry{config: ceuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ceuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collectionentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
