// Code generated by entc, DO NOT EDIT.

package ent

func (c *CollectionQuery) With(wf func(q *CollectionQuery)) *CollectionQuery {
	wf(c)
	return c
}

func (f *FeedQuery) With(wf func(q *FeedQuery)) *FeedQuery {
	wf(f)
	return f
}

func (u *UserQuery) With(wf func(q *UserQuery)) *UserQuery {
	wf(u)
	return u
}
