// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// CollectionEntry is the predicate function for collectionentry builders.
type CollectionEntry func(*sql.Selector)

// Entry is the predicate function for entry builders.
type Entry func(*sql.Selector)

// Feed is the predicate function for feed builders.
type Feed func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
